# Generated by Django 6.0.1 on 2026-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razmer', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
